// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Sap_login;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>SapValidation</b><br>
 * Generated     : <b>2018/09/11 4:07:44 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 10 amd64 10.0 <br>
 * 
 * @since  September 11, 2018
 * @author VenkatanarayanaS
 */
public abstract class SapValidationHelper extends RationalTestScript
{
	/**
	 * DataEntryView: with default state.
	 *		Name : ERFASSUNGSSICHT
	 * 		Id : /boxERFASSUNGSSICHT
	 * 		.class : GuiBox
	 */
	protected GuiTestObject _dataEntryView() 
	{
		return new GuiTestObject(
                        getMappedTestObject("_dataEntryView"));
	}
	/**
	 * DataEntryView: with specific test context and state.
	 *		Name : ERFASSUNGSSICHT
	 * 		Id : /boxERFASSUNGSSICHT
	 * 		.class : GuiBox
	 */
	protected GuiTestObject _dataEntryView(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("_dataEntryView"), anchor, flags);
	}
	
	/**
	 * Items: with default state.
	 *		Name : RM07M-POSIT
	 * 		Id : /boxRM07M-POSIT
	 * 		.class : GuiBox
	 */
	protected GuiTestObject _items() 
	{
		return new GuiTestObject(
                        getMappedTestObject("_items"));
	}
	/**
	 * Items: with specific test context and state.
	 *		Name : RM07M-POSIT
	 * 		Id : /boxRM07M-POSIT
	 * 		.class : GuiBox
	 */
	protected GuiTestObject _items(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("_items"), anchor, flags);
	}
	
	/**
	 * Items: with default state.
	 *		Name : RM07M-POSIT
	 * 		Id : /boxRM07M-POSIT
	 * 		.class : GuiBox
	 */
	protected GuiTestObject _items2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("_items2"));
	}
	/**
	 * Items: with specific test context and state.
	 *		Name : RM07M-POSIT
	 * 		Id : /boxRM07M-POSIT
	 * 		.class : GuiBox
	 */
	protected GuiTestObject _items2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("_items2"), anchor, flags);
	}
	
	/**
	 * Back: with default state.
	 *		Name : btn[3]
	 * 		Id : /btn[3]
	 * 		.class : GuiButton
	 */
	protected SAPGuiToggleTestObject button_back() 
	{
		return new SAPGuiToggleTestObject(
                        getMappedTestObject("button_back"));
	}
	/**
	 * Back: with specific test context and state.
	 *		Name : btn[3]
	 * 		Id : /btn[3]
	 * 		.class : GuiButton
	 */
	protected SAPGuiToggleTestObject button_back(TestObject anchor, long flags) 
	{
		return new SAPGuiToggleTestObject(
                        getMappedTestObject("button_back"), anchor, flags);
	}
	
	/**
	 * btn3: with default state.
	 *		Name : btn[3]
	 * 		Id : /btn[3]
	 * 		.class : GuiButton
	 */
	protected SAPGuiToggleTestObject button_btn3() 
	{
		return new SAPGuiToggleTestObject(
                        getMappedTestObject("button_btn3"));
	}
	/**
	 * btn3: with specific test context and state.
	 *		Name : btn[3]
	 * 		Id : /btn[3]
	 * 		.class : GuiButton
	 */
	protected SAPGuiToggleTestObject button_btn3(TestObject anchor, long flags) 
	{
		return new SAPGuiToggleTestObject(
                        getMappedTestObject("button_btn3"), anchor, flags);
	}
	
	/**
	 * DisplayDocHeaderDetails: with default state.
	 *		Name : BT_HEAD
	 * 		Id : /subSUBSCREEN_HEADER:SAPMV45A:4021/btnBT_HEAD
	 * 		.class : GuiButton
	 */
	protected SAPGuiToggleTestObject button_displayDocHeaderDetails() 
	{
		return new SAPGuiToggleTestObject(
                        getMappedTestObject("button_displayDocHeaderDetails"));
	}
	/**
	 * DisplayDocHeaderDetails: with specific test context and state.
	 *		Name : BT_HEAD
	 * 		Id : /subSUBSCREEN_HEADER:SAPMV45A:4021/btnBT_HEAD
	 * 		.class : GuiButton
	 */
	protected SAPGuiToggleTestObject button_displayDocHeaderDetails(TestObject anchor, long flags) 
	{
		return new SAPGuiToggleTestObject(
                        getMappedTestObject("button_displayDocHeaderDetails"), anchor, flags);
	}
	
	/**
	 * Execute: with default state.
	 *		Name : btn[8]
	 * 		Id : /btn[8]
	 * 		.class : GuiButton
	 */
	protected SAPGuiToggleTestObject button_execute() 
	{
		return new SAPGuiToggleTestObject(
                        getMappedTestObject("button_execute"));
	}
	/**
	 * Execute: with specific test context and state.
	 *		Name : btn[8]
	 * 		Id : /btn[8]
	 * 		.class : GuiButton
	 */
	protected SAPGuiToggleTestObject button_execute(TestObject anchor, long flags) 
	{
		return new SAPGuiToggleTestObject(
                        getMappedTestObject("button_execute"), anchor, flags);
	}
	
	/**
	 * SalesDocument500Entries: with default state.
	 *		Name : wnd[1]
	 * 		Text : Sales Document 500 Entries
	 * 		.connectionNumber : 0
	 * 		Id : /wnd[1]
	 * 		.class : GuiModalWindow
	 * 		.sessionNumber : 0
	 * 		.processName : saplogon.exe
	 */
	protected SAPTopLevelTestObject dialog_salesDocument500Entries() 
	{
		return new SAPTopLevelTestObject(
                        getMappedTestObject("dialog_salesDocument500Entries"));
	}
	/**
	 * SalesDocument500Entries: with specific test context and state.
	 *		Name : wnd[1]
	 * 		Text : Sales Document 500 Entries
	 * 		.connectionNumber : 0
	 * 		Id : /wnd[1]
	 * 		.class : GuiModalWindow
	 * 		.sessionNumber : 0
	 * 		.processName : saplogon.exe
	 */
	protected SAPTopLevelTestObject dialog_salesDocument500Entries(TestObject anchor, long flags) 
	{
		return new SAPTopLevelTestObject(
                        getMappedTestObject("dialog_salesDocument500Entries"), anchor, flags);
	}
	
	/**
	 * SAPGUIGridViewCtrl1: with default state.
	 *		Name : shell
	 * 		Id : /cntlORDERS_CONTROL/shellcont/shell
	 * 		.class : GuiShell.GridView
	 */
	protected SAPGuiCtrlGridViewTestObject grid_sapguiGridViewCtrl1() 
	{
		return new SAPGuiCtrlGridViewTestObject(
                        getMappedTestObject("grid_sapguiGridViewCtrl1"));
	}
	/**
	 * SAPGUIGridViewCtrl1: with specific test context and state.
	 *		Name : shell
	 * 		Id : /cntlORDERS_CONTROL/shellcont/shell
	 * 		.class : GuiShell.GridView
	 */
	protected SAPGuiCtrlGridViewTestObject grid_sapguiGridViewCtrl1(TestObject anchor, long flags) 
	{
		return new SAPGuiCtrlGridViewTestObject(
                        getMappedTestObject("grid_sapguiGridViewCtrl1"), anchor, flags);
	}
	
	/**
	 * SAPGUIGridViewCtrl1: with default state.
	 *		Name : shell
	 * 		Id : /cntlORDERS_CONTROL/shellcont/shell
	 * 		.class : GuiShell.GridView
	 */
	protected SAPGuiCtrlGridViewTestObject grid_sapguiGridViewCtrl1_2() 
	{
		return new SAPGuiCtrlGridViewTestObject(
                        getMappedTestObject("grid_sapguiGridViewCtrl1_2"));
	}
	/**
	 * SAPGUIGridViewCtrl1: with specific test context and state.
	 *		Name : shell
	 * 		Id : /cntlORDERS_CONTROL/shellcont/shell
	 * 		.class : GuiShell.GridView
	 */
	protected SAPGuiCtrlGridViewTestObject grid_sapguiGridViewCtrl1_2(TestObject anchor, long flags) 
	{
		return new SAPGuiCtrlGridViewTestObject(
                        getMappedTestObject("grid_sapguiGridViewCtrl1_2"), anchor, flags);
	}
	
	/**
	 * SAPGUIGridViewCtrl1: with default state.
	 *		Name : shell
	 * 		Id : /cntlCTRL_CONTAINERBSEG/shellcont/shell
	 * 		.class : GuiShell.GridView
	 */
	protected SAPGuiCtrlGridViewTestObject grid_sapguiGridViewCtrl1_3() 
	{
		return new SAPGuiCtrlGridViewTestObject(
                        getMappedTestObject("grid_sapguiGridViewCtrl1_3"));
	}
	/**
	 * SAPGUIGridViewCtrl1: with specific test context and state.
	 *		Name : shell
	 * 		Id : /cntlCTRL_CONTAINERBSEG/shellcont/shell
	 * 		.class : GuiShell.GridView
	 */
	protected SAPGuiCtrlGridViewTestObject grid_sapguiGridViewCtrl1_3(TestObject anchor, long flags) 
	{
		return new SAPGuiCtrlGridViewTestObject(
                        getMappedTestObject("grid_sapguiGridViewCtrl1_3"), anchor, flags);
	}
	
	/**
	 * Conditions: with default state.
	 *		Name : T\06
	 * 		Id : /tabpT\06
	 * 		.class : GuiTab
	 */
	protected SAPGuiTabTestObject pageTab_conditions() 
	{
		return new SAPGuiTabTestObject(
                        getMappedTestObject("pageTab_conditions"));
	}
	/**
	 * Conditions: with specific test context and state.
	 *		Name : T\06
	 * 		Id : /tabpT\06
	 * 		.class : GuiTab
	 */
	protected SAPGuiTabTestObject pageTab_conditions(TestObject anchor, long flags) 
	{
		return new SAPGuiTabTestObject(
                        getMappedTestObject("pageTab_conditions"), anchor, flags);
	}
	
	/**
	 * Conditions: with default state.
	 *		Name : T\06
	 * 		Id : /tabpT\06
	 * 		.class : GuiTab
	 */
	protected SAPGuiTabTestObject pageTab_conditions2() 
	{
		return new SAPGuiTabTestObject(
                        getMappedTestObject("pageTab_conditions2"));
	}
	/**
	 * Conditions: with specific test context and state.
	 *		Name : T\06
	 * 		Id : /tabpT\06
	 * 		.class : GuiTab
	 */
	protected SAPGuiTabTestObject pageTab_conditions2(TestObject anchor, long flags) 
	{
		return new SAPGuiTabTestObject(
                        getMappedTestObject("pageTab_conditions2"), anchor, flags);
	}
	
	/**
	 * ItemDetail: with default state.
	 *		Name : T\03
	 * 		Id : /tabpT\03
	 * 		.class : GuiTab
	 */
	protected SAPGuiTabTestObject pageTab_itemDetail() 
	{
		return new SAPGuiTabTestObject(
                        getMappedTestObject("pageTab_itemDetail"));
	}
	/**
	 * ItemDetail: with specific test context and state.
	 *		Name : T\03
	 * 		Id : /tabpT\03
	 * 		.class : GuiTab
	 */
	protected SAPGuiTabTestObject pageTab_itemDetail(TestObject anchor, long flags) 
	{
		return new SAPGuiTabTestObject(
                        getMappedTestObject("pageTab_itemDetail"), anchor, flags);
	}
	
	/**
	 * Partners: with default state.
	 *		Name : T\08
	 * 		Id : /tabpT\08
	 * 		.class : GuiTab
	 */
	protected SAPGuiTabTestObject pageTab_partners() 
	{
		return new SAPGuiTabTestObject(
                        getMappedTestObject("pageTab_partners"));
	}
	/**
	 * Partners: with specific test context and state.
	 *		Name : T\08
	 * 		Id : /tabpT\08
	 * 		.class : GuiTab
	 */
	protected SAPGuiTabTestObject pageTab_partners(TestObject anchor, long flags) 
	{
		return new SAPGuiTabTestObject(
                        getMappedTestObject("pageTab_partners"), anchor, flags);
	}
	
	/**
	 * PaymentCards: with default state.
	 *		Name : T\04
	 * 		Id : /tabpT\04
	 * 		.class : GuiTab
	 */
	protected SAPGuiTabTestObject pageTab_paymentCards() 
	{
		return new SAPGuiTabTestObject(
                        getMappedTestObject("pageTab_paymentCards"));
	}
	/**
	 * PaymentCards: with specific test context and state.
	 *		Name : T\04
	 * 		Id : /tabpT\04
	 * 		.class : GuiTab
	 */
	protected SAPGuiTabTestObject pageTab_paymentCards(TestObject anchor, long flags) 
	{
		return new SAPGuiTabTestObject(
                        getMappedTestObject("pageTab_paymentCards"), anchor, flags);
	}
	
	/**
	 * Sales: with default state.
	 *		Name : T\01
	 * 		Id : /tabpT\01
	 * 		.class : GuiTab
	 */
	protected SAPGuiTabTestObject pageTab_sales() 
	{
		return new SAPGuiTabTestObject(
                        getMappedTestObject("pageTab_sales"));
	}
	/**
	 * Sales: with specific test context and state.
	 *		Name : T\01
	 * 		Id : /tabpT\01
	 * 		.class : GuiTab
	 */
	protected SAPGuiTabTestObject pageTab_sales(TestObject anchor, long flags) 
	{
		return new SAPGuiTabTestObject(
                        getMappedTestObject("pageTab_sales"), anchor, flags);
	}
	
	/**
	 * usr: with default state.
	 *		Name : usr
	 * 		Id : /usr
	 * 		.class : GuiUserArea
	 */
	protected SAPGuiUserAreaTestObject panel_usr() 
	{
		return new SAPGuiUserAreaTestObject(
                        getMappedTestObject("panel_usr"));
	}
	/**
	 * usr: with specific test context and state.
	 *		Name : usr
	 * 		Id : /usr
	 * 		.class : GuiUserArea
	 */
	protected SAPGuiUserAreaTestObject panel_usr(TestObject anchor, long flags) 
	{
		return new SAPGuiUserAreaTestObject(
                        getMappedTestObject("panel_usr"), anchor, flags);
	}
	
	/**
	 * SAPLV09CGV_TC_PARTNER_OVERVIEW: with default state.
	 *		Name : SAPLV09CGV_TC_PARTNER_OVERVIEW
	 * 		Id : /ssubSUBSCREEN_BODY:SAPMV45A:4352/subSUBSCREEN_PARTNER_OVERVIEW:SAPLV09C:1000/tb ...
	 * 		.class : GuiTableControl
	 */
	protected SAPGuiTableControlTestObject partnertable_sap() 
	{
		return new SAPGuiTableControlTestObject(
                        getMappedTestObject("partnertable_sap"));
	}
	/**
	 * SAPLV09CGV_TC_PARTNER_OVERVIEW: with specific test context and state.
	 *		Name : SAPLV09CGV_TC_PARTNER_OVERVIEW
	 * 		Id : /ssubSUBSCREEN_BODY:SAPMV45A:4352/subSUBSCREEN_PARTNER_OVERVIEW:SAPLV09C:1000/tb ...
	 * 		.class : GuiTableControl
	 */
	protected SAPGuiTableControlTestObject partnertable_sap(TestObject anchor, long flags) 
	{
		return new SAPGuiTableControlTestObject(
                        getMappedTestObject("partnertable_sap"), anchor, flags);
	}
	
	/**
	 * SAPALVGrid: with default state.
	 *		.text : null
	 * 		.class : SAPALVGrid
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject sapalvGridwindow() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("sapalvGridwindow"));
	}
	/**
	 * SAPALVGrid: with specific test context and state.
	 *		.text : null
	 * 		.class : SAPALVGrid
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject sapalvGridwindow(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("sapalvGridwindow"), anchor, flags);
	}
	
	/**
	 * SysListView32: with default state.
	 *		.text : null
	 * 		.class : SysListView32
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject sysListView32table() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("sysListView32table"));
	}
	/**
	 * SysListView32: with specific test context and state.
	 *		.text : null
	 * 		.class : SysListView32
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject sysListView32table(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("sysListView32table"), anchor, flags);
	}
	
	/**
	 * SysListView32: with default state.
	 *		.text : null
	 * 		.class : SysListView32
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject sysListView32table2() 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("sysListView32table2"));
	}
	/**
	 * SysListView32: with specific test context and state.
	 *		.text : null
	 * 		.class : SysListView32
	 * 		.name : null
	 * 		.classIndex : 0
	 */
	protected SelectGuiSubitemTestObject sysListView32table2(TestObject anchor, long flags) 
	{
		return new SelectGuiSubitemTestObject(
                        getMappedTestObject("sysListView32table2"), anchor, flags);
	}
	
	/**
	 * AllItems: with default state.
	 *		Name : SAPMV45ATCTRL_U_ERF_AUFTRAG
	 * 		Id : /ssubSUBSCREEN_BODY:SAPMV45A:4400/subSUBSCREEN_TC:SAPMV45A:4900/tblSAPMV45ATCTRL ...
	 * 		.class : GuiTableControl
	 */
	protected SAPGuiTableControlTestObject table_allItems() 
	{
		return new SAPGuiTableControlTestObject(
                        getMappedTestObject("table_allItems"));
	}
	/**
	 * AllItems: with specific test context and state.
	 *		Name : SAPMV45ATCTRL_U_ERF_AUFTRAG
	 * 		Id : /ssubSUBSCREEN_BODY:SAPMV45A:4400/subSUBSCREEN_TC:SAPMV45A:4900/tblSAPMV45ATCTRL ...
	 * 		.class : GuiTableControl
	 */
	protected SAPGuiTableControlTestObject table_allItems(TestObject anchor, long flags) 
	{
		return new SAPGuiTableControlTestObject(
                        getMappedTestObject("table_allItems"), anchor, flags);
	}
	
	/**
	 * AllItems: with default state.
	 *		Name : SAPMV45ATCTRL_U_ERF_AUFTRAG
	 * 		Id : /ssubSUBSCREEN_BODY:SAPMV45A:4400/subSUBSCREEN_TC:SAPMV45A:4900/tblSAPMV45ATCTRL ...
	 * 		.class : GuiTableControl
	 */
	protected SAPGuiTableControlTestObject table_allItems2() 
	{
		return new SAPGuiTableControlTestObject(
                        getMappedTestObject("table_allItems2"));
	}
	/**
	 * AllItems: with specific test context and state.
	 *		Name : SAPMV45ATCTRL_U_ERF_AUFTRAG
	 * 		Id : /ssubSUBSCREEN_BODY:SAPMV45A:4400/subSUBSCREEN_TC:SAPMV45A:4900/tblSAPMV45ATCTRL ...
	 * 		.class : GuiTableControl
	 */
	protected SAPGuiTableControlTestObject table_allItems2(TestObject anchor, long flags) 
	{
		return new SAPGuiTableControlTestObject(
                        getMappedTestObject("table_allItems2"), anchor, flags);
	}
	
	/**
	 * PaymentCards: with default state.
	 *		Name : SAPLV60FTCTRL_ZAHLUNGSKARTEN
	 * 		Id : /ssubSUBSCREEN_BODY:SAPLV60F:4204/tblSAPLV60FTCTRL_ZAHLUNGSKARTEN
	 * 		.class : GuiTableControl
	 */
	protected SAPGuiTableControlTestObject table_paymentCards() 
	{
		return new SAPGuiTableControlTestObject(
                        getMappedTestObject("table_paymentCards"));
	}
	/**
	 * PaymentCards: with specific test context and state.
	 *		Name : SAPLV60FTCTRL_ZAHLUNGSKARTEN
	 * 		Id : /ssubSUBSCREEN_BODY:SAPLV60F:4204/tblSAPLV60FTCTRL_ZAHLUNGSKARTEN
	 * 		.class : GuiTableControl
	 */
	protected SAPGuiTableControlTestObject table_paymentCards(TestObject anchor, long flags) 
	{
		return new SAPGuiTableControlTestObject(
                        getMappedTestObject("table_paymentCards"), anchor, flags);
	}
	
	/**
	 * PricingElements: with default state.
	 *		Name : SAPLV69ATCTRL_KONDITIONEN
	 * 		Id : /ssubSUBSCREEN_BODY:SAPLV69A:6201/tblSAPLV69ATCTRL_KONDITIONEN
	 * 		.class : GuiTableControl
	 */
	protected SAPGuiTableControlTestObject table_pricingElements() 
	{
		return new SAPGuiTableControlTestObject(
                        getMappedTestObject("table_pricingElements"));
	}
	/**
	 * PricingElements: with specific test context and state.
	 *		Name : SAPLV69ATCTRL_KONDITIONEN
	 * 		Id : /ssubSUBSCREEN_BODY:SAPLV69A:6201/tblSAPLV69ATCTRL_KONDITIONEN
	 * 		.class : GuiTableControl
	 */
	protected SAPGuiTableControlTestObject table_pricingElements(TestObject anchor, long flags) 
	{
		return new SAPGuiTableControlTestObject(
                        getMappedTestObject("table_pricingElements"), anchor, flags);
	}
	
	/**
	 * SAPMV60ATCTRL_UEB_FAKT: with default state.
	 *		Name : SAPMV60ATCTRL_UEB_FAKT
	 * 		Id : /tblSAPMV60ATCTRL_UEB_FAKT
	 * 		.class : GuiTableControl
	 */
	protected SAPGuiTableControlTestObject table_sapmV60ATCTRL_UEB_FAKT() 
	{
		return new SAPGuiTableControlTestObject(
                        getMappedTestObject("table_sapmV60ATCTRL_UEB_FAKT"));
	}
	/**
	 * SAPMV60ATCTRL_UEB_FAKT: with specific test context and state.
	 *		Name : SAPMV60ATCTRL_UEB_FAKT
	 * 		Id : /tblSAPMV60ATCTRL_UEB_FAKT
	 * 		.class : GuiTableControl
	 */
	protected SAPGuiTableControlTestObject table_sapmV60ATCTRL_UEB_FAKT(TestObject anchor, long flags) 
	{
		return new SAPGuiTableControlTestObject(
                        getMappedTestObject("table_sapmV60ATCTRL_UEB_FAKT"), anchor, flags);
	}
	
	/**
	 * CCDATACCINS: with default state.
	 *		Name : CCDATA-CCINS
	 * 		Id : /ssubSUBSCREEN_BODY:SAPMV45A:4400/ssubHEADER_FRAME:SAPMV45A:4440/ctxtCCDATA-CCIN ...
	 * 		.class : GuiCTextField
	 * 		.priorLabel : Payment card
	 */
	protected SAPGuiTextTestObject text_ccdataccins() 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_ccdataccins"));
	}
	/**
	 * CCDATACCINS: with specific test context and state.
	 *		Name : CCDATA-CCINS
	 * 		Id : /ssubSUBSCREEN_BODY:SAPMV45A:4400/ssubHEADER_FRAME:SAPMV45A:4440/ctxtCCDATA-CCIN ...
	 * 		.class : GuiCTextField
	 * 		.priorLabel : Payment card
	 */
	protected SAPGuiTextTestObject text_ccdataccins(TestObject anchor, long flags) 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_ccdataccins"), anchor, flags);
	}
	
	/**
	 * CCDATACCNUM: with default state.
	 *		Name : CCDATA-CCNUM
	 * 		Id : /ssubSUBSCREEN_BODY:SAPMV45A:4400/ssubHEADER_FRAME:SAPMV45A:4440/ctxtCCDATA-CCNU ...
	 * 		.class : GuiCTextField
	 */
	protected SAPGuiTextTestObject text_ccdataccnum() 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_ccdataccnum"));
	}
	/**
	 * CCDATACCNUM: with specific test context and state.
	 *		Name : CCDATA-CCNUM
	 * 		Id : /ssubSUBSCREEN_BODY:SAPMV45A:4400/ssubHEADER_FRAME:SAPMV45A:4440/ctxtCCDATA-CCNU ...
	 * 		.class : GuiCTextField
	 */
	protected SAPGuiTextTestObject text_ccdataccnum(TestObject anchor, long flags) 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_ccdataccnum"), anchor, flags);
	}
	
	/**
	 * DM07MVZBEW: with default state.
	 *		Name : DM07M-VZBEW
	 * 		Id : /sub:SAPMM07M:0420/ctxtDM07M-VZBEW[0,79]
	 * 		.class : GuiCTextField
	 */
	protected SAPGuiTextTestObject text_dM07MVZBEW() 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_dM07MVZBEW"));
	}
	/**
	 * DM07MVZBEW: with specific test context and state.
	 *		Name : DM07M-VZBEW
	 * 		Id : /sub:SAPMM07M:0420/ctxtDM07M-VZBEW[0,79]
	 * 		.class : GuiCTextField
	 */
	protected SAPGuiTextTestObject text_dM07MVZBEW(TestObject anchor, long flags) 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_dM07MVZBEW"), anchor, flags);
	}
	
	/**
	 * KUWEVTXTPA: with default state.
	 *		Name : KUWEV-TXTPA
	 * 		Id : /subSUBSCREEN_HEADER:SAPMV45A:4021/subPART-SUB:SAPMV45A:4701/txtKUWEV-TXTPA
	 * 		.class : GuiTextField
	 */
	protected SAPGuiTextTestObject text_kuwevtxtpa() 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_kuwevtxtpa"));
	}
	/**
	 * KUWEVTXTPA: with specific test context and state.
	 *		Name : KUWEV-TXTPA
	 * 		Id : /subSUBSCREEN_HEADER:SAPMV45A:4021/subPART-SUB:SAPMV45A:4701/txtKUWEV-TXTPA
	 * 		.class : GuiTextField
	 */
	protected SAPGuiTextTestObject text_kuwevtxtpa(TestObject anchor, long flags) 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_kuwevtxtpa"), anchor, flags);
	}
	
	/**
	 * MSEGBWART: with default state.
	 *		Name : MSEG-BWART
	 * 		Id : /sub:SAPMM07M:0420/ctxtMSEG-BWART[0,73]
	 * 		.class : GuiCTextField
	 */
	protected SAPGuiTextTestObject text_msegbwart() 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_msegbwart"));
	}
	/**
	 * MSEGBWART: with specific test context and state.
	 *		Name : MSEG-BWART
	 * 		Id : /sub:SAPMM07M:0420/ctxtMSEG-BWART[0,73]
	 * 		.class : GuiCTextField
	 */
	protected SAPGuiTextTestObject text_msegbwart(TestObject anchor, long flags) 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_msegbwart"), anchor, flags);
	}
	
	/**
	 * MSEGERFME: with default state.
	 *		Name : MSEG-ERFME
	 * 		Id : /sub:SAPMM07M:0420/ctxtMSEG-ERFME[0,23]
	 * 		.class : GuiCTextField
	 */
	protected SAPGuiTextTestObject text_msegerfme() 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_msegerfme"));
	}
	/**
	 * MSEGERFME: with specific test context and state.
	 *		Name : MSEG-ERFME
	 * 		Id : /sub:SAPMM07M:0420/ctxtMSEG-ERFME[0,23]
	 * 		.class : GuiCTextField
	 */
	protected SAPGuiTextTestObject text_msegerfme(TestObject anchor, long flags) 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_msegerfme"), anchor, flags);
	}
	
	/**
	 * MSEGERFMG: with default state.
	 *		Name : MSEG-ERFMG
	 * 		Id : /sub:SAPMM07M:0420/txtMSEG-ERFMG[0,5]
	 * 		.class : GuiTextField
	 */
	protected SAPGuiTextTestObject text_msegerfmg() 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_msegerfmg"));
	}
	/**
	 * MSEGERFMG: with specific test context and state.
	 *		Name : MSEG-ERFMG
	 * 		Id : /sub:SAPMM07M:0420/txtMSEG-ERFMG[0,5]
	 * 		.class : GuiTextField
	 */
	protected SAPGuiTextTestObject text_msegerfmg(TestObject anchor, long flags) 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_msegerfmg"), anchor, flags);
	}
	
	/**
	 * MSEGLGORT: with default state.
	 *		Name : MSEG-LGORT
	 * 		Id : /sub:SAPMM07M:0420/ctxtMSEG-LGORT[0,53]
	 * 		.class : GuiCTextField
	 */
	protected SAPGuiTextTestObject text_mseglgort() 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_mseglgort"));
	}
	/**
	 * MSEGLGORT: with specific test context and state.
	 *		Name : MSEG-LGORT
	 * 		Id : /sub:SAPMM07M:0420/ctxtMSEG-LGORT[0,53]
	 * 		.class : GuiCTextField
	 */
	protected SAPGuiTextTestObject text_mseglgort(TestObject anchor, long flags) 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_mseglgort"), anchor, flags);
	}
	
	/**
	 * MSEGMATNR: with default state.
	 *		Name : MSEG-MATNR
	 * 		Id : /sub:SAPMM07M:0420/ctxtMSEG-MATNR[0,27]
	 * 		.class : GuiCTextField
	 */
	protected SAPGuiTextTestObject text_msegmatnr() 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_msegmatnr"));
	}
	/**
	 * MSEGMATNR: with specific test context and state.
	 *		Name : MSEG-MATNR
	 * 		Id : /sub:SAPMM07M:0420/ctxtMSEG-MATNR[0,27]
	 * 		.class : GuiCTextField
	 */
	protected SAPGuiTextTestObject text_msegmatnr(TestObject anchor, long flags) 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_msegmatnr"), anchor, flags);
	}
	
	/**
	 * MSEGWERKS: with default state.
	 *		Name : MSEG-WERKS
	 * 		Id : /sub:SAPMM07M:0420/ctxtMSEG-WERKS[0,47]
	 * 		.class : GuiCTextField
	 */
	protected SAPGuiTextTestObject text_msegwerks() 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_msegwerks"));
	}
	/**
	 * MSEGWERKS: with specific test context and state.
	 *		Name : MSEG-WERKS
	 * 		Id : /sub:SAPMM07M:0420/ctxtMSEG-WERKS[0,47]
	 * 		.class : GuiCTextField
	 */
	protected SAPGuiTextTestObject text_msegwerks(TestObject anchor, long flags) 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_msegwerks"), anchor, flags);
	}
	
	/**
	 * MSEGZEILE: with default state.
	 *		Name : MSEG-ZEILE
	 * 		Id : /sub:SAPMM07M:0420/txtMSEG-ZEILE[0,0]
	 * 		.class : GuiTextField
	 * 		.priorLabel : FIs
	 */
	protected SAPGuiTextTestObject text_msegzeile() 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_msegzeile"));
	}
	/**
	 * MSEGZEILE: with specific test context and state.
	 *		Name : MSEG-ZEILE
	 * 		Id : /sub:SAPMM07M:0420/txtMSEG-ZEILE[0,0]
	 * 		.class : GuiTextField
	 * 		.priorLabel : FIs
	 */
	protected SAPGuiTextTestObject text_msegzeile(TestObject anchor, long flags) 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_msegzeile"), anchor, flags);
	}
	
	/**
	 * MSEGZEILE: with default state.
	 *		Name : MSEG-ZEILE
	 * 		Id : /sub:SAPMM07M:0420/txtMSEG-ZEILE[0,0]
	 * 		.class : GuiTextField
	 * 		.priorLabel : FIs
	 */
	protected SAPGuiTextTestObject text_msegzeile2() 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_msegzeile2"));
	}
	/**
	 * MSEGZEILE: with specific test context and state.
	 *		Name : MSEG-ZEILE
	 * 		Id : /sub:SAPMM07M:0420/txtMSEG-ZEILE[0,0]
	 * 		.class : GuiTextField
	 * 		.priorLabel : FIs
	 */
	protected SAPGuiTextTestObject text_msegzeile2(TestObject anchor, long flags) 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_msegzeile2"), anchor, flags);
	}
	
	/**
	 * RV45AKWMENG: with default state.
	 *		Name : RV45A-KWMENG
	 * 		Id : /txtRV45A-KWMENG[2,0]
	 * 		.class : GuiTextField
	 * 		.priorLabel : Order Quantity
	 */
	protected SAPGuiTextTestObject text_rV45AKWMENG() 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_rV45AKWMENG"));
	}
	/**
	 * RV45AKWMENG: with specific test context and state.
	 *		Name : RV45A-KWMENG
	 * 		Id : /txtRV45A-KWMENG[2,0]
	 * 		.class : GuiTextField
	 * 		.priorLabel : Order Quantity
	 */
	protected SAPGuiTextTestObject text_rV45AKWMENG(TestObject anchor, long flags) 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_rV45AKWMENG"), anchor, flags);
	}
	
	/**
	 * RV45AKWMENG: with default state.
	 *		Name : RV45A-KWMENG
	 * 		Id : /txtRV45A-KWMENG[2,0]
	 * 		.class : GuiTextField
	 * 		.priorLabel : Order Quantity
	 */
	protected SAPGuiTextTestObject text_rV45AKWMENG2() 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_rV45AKWMENG2"));
	}
	/**
	 * RV45AKWMENG: with specific test context and state.
	 *		Name : RV45A-KWMENG
	 * 		Id : /txtRV45A-KWMENG[2,0]
	 * 		.class : GuiTextField
	 * 		.priorLabel : Order Quantity
	 */
	protected SAPGuiTextTestObject text_rV45AKWMENG2(TestObject anchor, long flags) 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_rV45AKWMENG2"), anchor, flags);
	}
	
	/**
	 * RV45AKWMENG: with default state.
	 *		Name : RV45A-KWMENG
	 * 		Id : /txtRV45A-KWMENG[2,0]
	 * 		.class : GuiTextField
	 * 		.priorLabel : Order Quantity
	 */
	protected SAPGuiTextTestObject text_rV45AKWMENG3() 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_rV45AKWMENG3"));
	}
	/**
	 * RV45AKWMENG: with specific test context and state.
	 *		Name : RV45A-KWMENG
	 * 		Id : /txtRV45A-KWMENG[2,0]
	 * 		.class : GuiTextField
	 * 		.priorLabel : Order Quantity
	 */
	protected SAPGuiTextTestObject text_rV45AKWMENG3(TestObject anchor, long flags) 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_rV45AKWMENG3"), anchor, flags);
	}
	
	/**
	 * RV45AMABNR: with default state.
	 *		Name : RV45A-MABNR
	 * 		Id : /ctxtRV45A-MABNR[1,0]
	 * 		.class : GuiCTextField
	 * 		.priorLabel : Article
	 */
	protected SAPGuiTextTestObject text_rV45AMABNR() 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_rV45AMABNR"));
	}
	/**
	 * RV45AMABNR: with specific test context and state.
	 *		Name : RV45A-MABNR
	 * 		Id : /ctxtRV45A-MABNR[1,0]
	 * 		.class : GuiCTextField
	 * 		.priorLabel : Article
	 */
	protected SAPGuiTextTestObject text_rV45AMABNR(TestObject anchor, long flags) 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_rV45AMABNR"), anchor, flags);
	}
	
	/**
	 * RV45AMABNR: with default state.
	 *		Name : RV45A-MABNR
	 * 		Id : /ctxtRV45A-MABNR[1,0]
	 * 		.class : GuiCTextField
	 * 		.priorLabel : Article
	 */
	protected SAPGuiTextTestObject text_rV45AMABNR2() 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_rV45AMABNR2"));
	}
	/**
	 * RV45AMABNR: with specific test context and state.
	 *		Name : RV45A-MABNR
	 * 		Id : /ctxtRV45A-MABNR[1,0]
	 * 		.class : GuiCTextField
	 * 		.priorLabel : Article
	 */
	protected SAPGuiTextTestObject text_rV45AMABNR2(TestObject anchor, long flags) 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_rV45AMABNR2"), anchor, flags);
	}
	
	/**
	 * RV45ATXT_VTRBER: with default state.
	 *		Name : RV45A-TXT_VTRBER
	 * 		Id : /ssubSUBSCREEN_BODY:SAPMV45A:4400/ssubHEADER_FRAME:SAPMV45A:4440/txtRV45A-TXT_VT ...
	 * 		.class : GuiTextField
	 */
	protected SAPGuiTextTestObject text_rV45ATXT_VTRBER() 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_rV45ATXT_VTRBER"));
	}
	/**
	 * RV45ATXT_VTRBER: with specific test context and state.
	 *		Name : RV45A-TXT_VTRBER
	 * 		Id : /ssubSUBSCREEN_BODY:SAPMV45A:4400/ssubHEADER_FRAME:SAPMV45A:4440/txtRV45A-TXT_VT ...
	 * 		.class : GuiTextField
	 */
	protected SAPGuiTextTestObject text_rV45ATXT_VTRBER(TestObject anchor, long flags) 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_rV45ATXT_VTRBER"), anchor, flags);
	}
	
	/**
	 * RSYSTBCODE: with default state.
	 *		Name : RSYST-BCODE
	 * 		Id : /pwdRSYST-BCODE
	 * 		.class : GuiPasswordField
	 * 		.priorLabel : Password
	 */
	protected SAPGuiTextTestObject text_rsystbcode() 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_rsystbcode"));
	}
	/**
	 * RSYSTBCODE: with specific test context and state.
	 *		Name : RSYST-BCODE
	 * 		Id : /pwdRSYST-BCODE
	 * 		.class : GuiPasswordField
	 * 		.priorLabel : Password
	 */
	protected SAPGuiTextTestObject text_rsystbcode(TestObject anchor, long flags) 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_rsystbcode"), anchor, flags);
	}
	
	/**
	 * RSYSTBNAME: with default state.
	 *		Name : RSYST-BNAME
	 * 		Id : /txtRSYST-BNAME
	 * 		.class : GuiTextField
	 * 		.priorLabel : User
	 */
	protected SAPGuiTextTestObject text_rsystbname() 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_rsystbname"));
	}
	/**
	 * RSYSTBNAME: with specific test context and state.
	 *		Name : RSYST-BNAME
	 * 		Id : /txtRSYST-BNAME
	 * 		.class : GuiTextField
	 * 		.priorLabel : User
	 */
	protected SAPGuiTextTestObject text_rsystbname(TestObject anchor, long flags) 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_rsystbname"), anchor, flags);
	}
	
	/**
	 * S_WEBORDLOW: with default state.
	 *		Name : S_WEBORD-LOW
	 * 		Id : /txtS_WEBORD-LOW
	 * 		.class : GuiTextField
	 */
	protected SAPGuiTextTestObject text_s_WEBORDLOW() 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_s_WEBORDLOW"));
	}
	/**
	 * S_WEBORDLOW: with specific test context and state.
	 *		Name : S_WEBORD-LOW
	 * 		Id : /txtS_WEBORD-LOW
	 * 		.class : GuiTextField
	 */
	protected SAPGuiTextTestObject text_s_WEBORDLOW(TestObject anchor, long flags) 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_s_WEBORDLOW"), anchor, flags);
	}
	
	/**
	 * VBAKNETWR: with default state.
	 *		Name : VBAK-NETWR
	 * 		Id : /subSUBSCREEN_HEADER:SAPMV45A:4021/txtVBAK-NETWR
	 * 		.class : GuiTextField
	 * 		.priorLabel : Net value
	 */
	protected SAPGuiTextTestObject text_vbaknetwr() 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_vbaknetwr"));
	}
	/**
	 * VBAKNETWR: with specific test context and state.
	 *		Name : VBAK-NETWR
	 * 		Id : /subSUBSCREEN_HEADER:SAPMV45A:4021/txtVBAK-NETWR
	 * 		.class : GuiTextField
	 * 		.priorLabel : Net value
	 */
	protected SAPGuiTextTestObject text_vbaknetwr(TestObject anchor, long flags) 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_vbaknetwr"), anchor, flags);
	}
	
	/**
	 * VBAKNETWR: with default state.
	 *		Name : VBAK-NETWR
	 * 		Id : /subSUBSCREEN_HEADER:SAPMV45A:4021/txtVBAK-NETWR
	 * 		.class : GuiTextField
	 * 		.priorLabel : Net value
	 */
	protected SAPGuiTextTestObject text_vbaknetwr2() 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_vbaknetwr2"));
	}
	/**
	 * VBAKNETWR: with specific test context and state.
	 *		Name : VBAK-NETWR
	 * 		Id : /subSUBSCREEN_HEADER:SAPMV45A:4021/txtVBAK-NETWR
	 * 		.class : GuiTextField
	 * 		.priorLabel : Net value
	 */
	protected SAPGuiTextTestObject text_vbaknetwr2(TestObject anchor, long flags) 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_vbaknetwr2"), anchor, flags);
	}
	
	/**
	 * VBAKSPART: with default state.
	 *		Name : VBAK-SPART
	 * 		Id : /ssubSUBSCREEN_BODY:SAPMV45A:4400/ssubHEADER_FRAME:SAPMV45A:4440/ctxtVBAK-SPART
	 * 		.class : GuiCTextField
	 * 		.priorLabel : /
	 */
	protected SAPGuiTextTestObject text_vbakspart() 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_vbakspart"));
	}
	/**
	 * VBAKSPART: with specific test context and state.
	 *		Name : VBAK-SPART
	 * 		Id : /ssubSUBSCREEN_BODY:SAPMV45A:4400/ssubHEADER_FRAME:SAPMV45A:4440/ctxtVBAK-SPART
	 * 		.class : GuiCTextField
	 * 		.priorLabel : /
	 */
	protected SAPGuiTextTestObject text_vbakspart(TestObject anchor, long flags) 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_vbakspart"), anchor, flags);
	}
	
	/**
	 * VBAKVKORG: with default state.
	 *		Name : VBAK-VKORG
	 * 		Id : /ssubSUBSCREEN_BODY:SAPMV45A:4400/ssubHEADER_FRAME:SAPMV45A:4440/ctxtVBAK-VKORG
	 * 		.class : GuiCTextField
	 * 		.priorLabel : Sales area
	 */
	protected SAPGuiTextTestObject text_vbakvkorg() 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_vbakvkorg"));
	}
	/**
	 * VBAKVKORG: with specific test context and state.
	 *		Name : VBAK-VKORG
	 * 		Id : /ssubSUBSCREEN_BODY:SAPMV45A:4400/ssubHEADER_FRAME:SAPMV45A:4440/ctxtVBAK-VKORG
	 * 		.class : GuiCTextField
	 * 		.priorLabel : Sales area
	 */
	protected SAPGuiTextTestObject text_vbakvkorg(TestObject anchor, long flags) 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_vbakvkorg"), anchor, flags);
	}
	
	/**
	 * VBAKVTWEG: with default state.
	 *		Name : VBAK-VTWEG
	 * 		Id : /ssubSUBSCREEN_BODY:SAPMV45A:4400/ssubHEADER_FRAME:SAPMV45A:4440/ctxtVBAK-VTWEG
	 * 		.class : GuiCTextField
	 * 		.priorLabel : /
	 */
	protected SAPGuiTextTestObject text_vbakvtweg() 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_vbakvtweg"));
	}
	/**
	 * VBAKVTWEG: with specific test context and state.
	 *		Name : VBAK-VTWEG
	 * 		Id : /ssubSUBSCREEN_BODY:SAPMV45A:4400/ssubHEADER_FRAME:SAPMV45A:4440/ctxtVBAK-VTWEG
	 * 		.class : GuiCTextField
	 * 		.priorLabel : /
	 */
	protected SAPGuiTextTestObject text_vbakvtweg(TestObject anchor, long flags) 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_vbakvtweg"), anchor, flags);
	}
	
	/**
	 * VBAPARKTX: with default state.
	 *		Name : VBAP-ARKTX
	 * 		Id : /txtVBAP-ARKTX[5,0]
	 * 		.class : GuiTextField
	 * 		.priorLabel : Description
	 */
	protected SAPGuiTextTestObject text_vbaparktx() 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_vbaparktx"));
	}
	/**
	 * VBAPARKTX: with specific test context and state.
	 *		Name : VBAP-ARKTX
	 * 		Id : /txtVBAP-ARKTX[5,0]
	 * 		.class : GuiTextField
	 * 		.priorLabel : Description
	 */
	protected SAPGuiTextTestObject text_vbaparktx(TestObject anchor, long flags) 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_vbaparktx"), anchor, flags);
	}
	
	/**
	 * VBAPWERKS: with default state.
	 *		Name : VBAP-WERKS
	 * 		Id : /ssubSUBSCREEN_BODY:SAPMV45A:4490/ssubITEM_FRAME:SAPMV45A:4480/ctxtVBAP-WERKS
	 * 		.class : GuiCTextField
	 * 		.priorLabel : Site
	 */
	protected SAPGuiTextTestObject text_vbapwerks() 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_vbapwerks"));
	}
	/**
	 * VBAPWERKS: with specific test context and state.
	 *		Name : VBAP-WERKS
	 * 		Id : /ssubSUBSCREEN_BODY:SAPMV45A:4490/ssubITEM_FRAME:SAPMV45A:4480/ctxtVBAP-WERKS
	 * 		.class : GuiCTextField
	 * 		.priorLabel : Site
	 */
	protected SAPGuiTextTestObject text_vbapwerks(TestObject anchor, long flags) 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("text_vbapwerks"), anchor, flags);
	}
	
	/**
	 * SAPTableTreeControl1: with default state.
	 *		Name : shell
	 * 		Id : /cntlIMAGE_CONTAINER/shellcont/shell/shellcont[0]/shell
	 * 		.class : GuiShell.Tree
	 */
	protected SAPGuiCtrlTreeTestObject tree_sapTableTreeControl1() 
	{
		return new SAPGuiCtrlTreeTestObject(
                        getMappedTestObject("tree_sapTableTreeControl1"));
	}
	/**
	 * SAPTableTreeControl1: with specific test context and state.
	 *		Name : shell
	 * 		Id : /cntlIMAGE_CONTAINER/shellcont/shell/shellcont[0]/shell
	 * 		.class : GuiShell.Tree
	 */
	protected SAPGuiCtrlTreeTestObject tree_sapTableTreeControl1(TestObject anchor, long flags) 
	{
		return new SAPGuiCtrlTreeTestObject(
                        getMappedTestObject("tree_sapTableTreeControl1"), anchor, flags);
	}
	
	/**
	 * SAPTableTreeControl1: with default state.
	 *		Name : shell
	 * 		Id : /cntlIMAGE_CONTAINER/shellcont/shell/shellcont[0]/shell
	 * 		.class : GuiShell.Tree
	 */
	protected SAPGuiCtrlTreeTestObject tree_sapTableTreeControl1_2() 
	{
		return new SAPGuiCtrlTreeTestObject(
                        getMappedTestObject("tree_sapTableTreeControl1_2"));
	}
	/**
	 * SAPTableTreeControl1: with specific test context and state.
	 *		Name : shell
	 * 		Id : /cntlIMAGE_CONTAINER/shellcont/shell/shellcont[0]/shell
	 * 		.class : GuiShell.Tree
	 */
	protected SAPGuiCtrlTreeTestObject tree_sapTableTreeControl1_2(TestObject anchor, long flags) 
	{
		return new SAPGuiCtrlTreeTestObject(
                        getMappedTestObject("tree_sapTableTreeControl1_2"), anchor, flags);
	}
	
	/**
	 * DisplayArticleDocument4995472592Overview: with default state.
	 *		Name : wnd[0]
	 * 		Text : Display Article Document 4995472592 : Overview
	 * 		.connectionNumber : 0
	 * 		Id : /wnd[0]
	 * 		.class : GuiMainWindow
	 * 		.sessionNumber : 0
	 * 		.processName : saplogon.exe
	 */
	protected SAPTopLevelTestObject window_displayArticleDocument4() 
	{
		return new SAPTopLevelTestObject(
                        getMappedTestObject("window_displayArticleDocument4"));
	}
	/**
	 * DisplayArticleDocument4995472592Overview: with specific test context and state.
	 *		Name : wnd[0]
	 * 		Text : Display Article Document 4995472592 : Overview
	 * 		.connectionNumber : 0
	 * 		Id : /wnd[0]
	 * 		.class : GuiMainWindow
	 * 		.sessionNumber : 0
	 * 		.processName : saplogon.exe
	 */
	protected SAPTopLevelTestObject window_displayArticleDocument4(TestObject anchor, long flags) 
	{
		return new SAPTopLevelTestObject(
                        getMappedTestObject("window_displayArticleDocument4"), anchor, flags);
	}
	
	/**
	 * DisplayStdOrderDirect1086885710Overview: with default state.
	 *		Name : wnd[0]
	 * 		.connectionNumber : 0
	 * 		Text : Display Std Order - Direct 1086885710: Overview
	 * 		Id : /wnd[0]
	 * 		.class : GuiMainWindow
	 * 		.sessionNumber : 0
	 * 		.processName : saplogon.exe
	 */
	protected SAPTopLevelTestObject window_displayStdOrderDirect10() 
	{
		return new SAPTopLevelTestObject(
                        getMappedTestObject("window_displayStdOrderDirect10"));
	}
	/**
	 * DisplayStdOrderDirect1086885710Overview: with specific test context and state.
	 *		Name : wnd[0]
	 * 		.connectionNumber : 0
	 * 		Text : Display Std Order - Direct 1086885710: Overview
	 * 		Id : /wnd[0]
	 * 		.class : GuiMainWindow
	 * 		.sessionNumber : 0
	 * 		.processName : saplogon.exe
	 */
	protected SAPTopLevelTestObject window_displayStdOrderDirect10(TestObject anchor, long flags) 
	{
		return new SAPTopLevelTestObject(
                        getMappedTestObject("window_displayStdOrderDirect10"), anchor, flags);
	}
	
	/**
	 * SAP: with default state.
	 *		Name : wnd[0]
	 * 		Text : SAP
	 * 		.connectionNumber : 4
	 * 		Id : /wnd[0]
	 * 		.class : GuiMainWindow
	 * 		.sessionNumber : 0
	 * 		.processName : saplogon.exe
	 */
	protected SAPTopLevelTestObject window_sap5() 
	{
		return new SAPTopLevelTestObject(
                        getMappedTestObject("window_sap5"));
	}
	/**
	 * SAP: with specific test context and state.
	 *		Name : wnd[0]
	 * 		Text : SAP
	 * 		.connectionNumber : 4
	 * 		Id : /wnd[0]
	 * 		.class : GuiMainWindow
	 * 		.sessionNumber : 0
	 * 		.processName : saplogon.exe
	 */
	protected SAPTopLevelTestObject window_sap5(TestObject anchor, long flags) 
	{
		return new SAPTopLevelTestObject(
                        getMappedTestObject("window_sap5"), anchor, flags);
	}
	
	/**
	 * Locate and return the verification point MSEGZEILE_standard object in the SUT.
	 */
	protected IFtVerificationPoint MSEGZEILE_standardVP() 
	{
		return vp("MSEGZEILE_standard");
	}
	protected IFtVerificationPoint MSEGZEILE_standardVP(TestObject anchor)
	{
		return vp("MSEGZEILE_standard", anchor);
	}
	
	/**
	 * Locate and return the verification point OrderQtyVP object in the SUT.
	 */
	protected IFtVerificationPoint OrderQtyVPVP() 
	{
		return vp("OrderQtyVP");
	}
	protected IFtVerificationPoint OrderQtyVPVP(TestObject anchor)
	{
		return vp("OrderQtyVP", anchor);
	}
	
	

	protected SapValidationHelper()
	{
		setScriptName("Sap_login.SapValidation");
	}
	
}

